blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^index/', bv.index),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

blog/views.py
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from . import models


def index(request):
    # return HttpResponse('Hello')
    # return render(request, 'blog/index.html', {'hello': 'hello blog'})
    # article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'Title')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.create(title=title, content=content)

    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>

blog/templates/blog/edit_page.html
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
    <label>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{ article.content }}"/>
    </label>
    <br/>

    <input type="submit" value="提交">
</form>

blog/templates/blog/index.html
<h1><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h1>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}